name: AntiDonkeyDupe
main: me.tiger.antiDonkeyDupe.AntiDonkeyDupe
version: 1.0.0
api-version: "1.21"
author: 2b2t_names
description: Prevent donkey/mule/llama chest dupes by virtualizing storage on entity unload/load.